In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
import numpy as np
from decision_tree import calculate_information_gain, decision_tree_train, decision_tree_predict
from naive_bayes import naive_bayes_train, naive_bayes_predict
from load_all_data import load_all_data


In [3]:
num_words, num_training, num_testing, train_data, test_data, train_labels, test_labels = load_all_data()

Found pickle file. Loading 20news data from file.
Doing so should be faster than loading from raw text, but if the file is corrupted, delete it and this script will automatically load from the raw text next time it is run.
Finished loading in 0.01 seconds.


In [4]:
d = 5000 # maximum number of features

In [4]:
# Filter features by information gain

gain = calculate_information_gain(train_data, train_labels)

print(gain)

# sort features by calculated information gain
ranks = gain.argsort()[::-1]

train_data = train_data[ranks[:d], :]
test_data = test_data[ranks[:d], :]

# convert training data to dense ndarray
train_data = train_data.toarray()
test_data = test_data.toarray()

[6.89207785e-03 5.72929455e-03 2.35420535e-02 ... 1.76640647e-12
 1.76640647e-12 1.76640647e-12]


NameError: name 'd' is not defined

In [98]:
# Try naive Bayes with hard-coded alpha value

nb_params = { 'alpha': 1.0 }

nb_model = naive_bayes_train(train_data, train_labels, nb_params)




num_of_classes 20
prior_smoothed, sum(prior_smoothed) , size
[0.043 0.052 0.051 0.052 0.051 0.053 0.052 0.053 0.053 0.053 0.053 0.053
 0.052 0.053 0.053 0.053 0.048 0.05  0.041 0.033] 1.0000000000000002 20
prior_smoothed_loged
 [-3.156 -2.965 -2.981 -2.955 -2.975 -2.946 -2.963 -2.946 -2.94  -2.943
 -2.936 -2.943 -2.948 -2.943 -2.945 -2.935 -3.029 -2.995 -3.19  -3.399]
Calculating column_sum, label: 0
Calculating column_sum, label: 1
Calculating column_sum, label: 2
Calculating column_sum, label: 3
Calculating column_sum, label: 4
Calculating column_sum, label: 5
Calculating column_sum, label: 6
Calculating column_sum, label: 7
Calculating column_sum, label: 8
Calculating column_sum, label: 9
Calculating column_sum, label: 10
Calculating column_sum, label: 11
Calculating column_sum, label: 12
Calculating column_sum, label: 13
Calculating column_sum, label: 14
Calculating column_sum, label: 15
Calculating column_sum, label: 16
Calculating column_sum, label: 17
Calculating column_sum, lab

In [109]:
# Compute training accuracy

nb_train_predictions = naive_bayes_predict(train_data, nb_model)

nb_train_accuracy = np.mean(nb_train_predictions == train_labels)

print("Naive Bayes training accuracy: %f" % nb_train_accuracy)

print(train_labels[0:20])

data
 [[ True False False ...  True False False]
 [False False False ... False False False]
 [False False False ... False False False]
 ...
 [False False False ... False False False]
 [False False False ... False False False]
 [False False False ... False False False]]
data_bar
 [[0 1 1 ... 0 1 1]
 [1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 ...
 [1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]]
cond prob
 [[0.351 0.014 0.007 ... 0.042 0.047 0.336]
 [0.002 0.099 0.638 ... 0.011 0.015 0.003]
 [0.002 0.002 0.012 ... 0.002 0.006 0.005]
 ...
 [0.002 0.003 0.002 ... 0.007 0.011 0.003]
 [0.006 0.003 0.019 ... 0.019 0.004 0.005]
 [0.002 0.002 0.002 ... 0.002 0.002 0.026]]
cond prob shape (5000, 20)
cond_prob_bar
 [[0.649 0.986 0.993 ... 0.958 0.953 0.664]
 [0.998 0.901 0.362 ... 0.989 0.985 0.997]
 [0.998 0.998 0.988 ... 0.998 0.994 0.995]
 ...
 [0.998 0.997 0.998 ... 0.993 0.989 0.997]
 [0.994 0.997 0.981 ... 0.981 0.996 0.995]
 [0.998 0.998 0.998 ... 0.998 0.998 0.974]]
cond_prob_bar shape

In [111]:
# Compute testing accuracy

nb_test_predictions = naive_bayes_predict(test_data, nb_model)

nb_test_accuracy = np.mean(nb_test_predictions == test_labels)

print("Naive Bayes testing accuracy: %f" % nb_test_accuracy)

data
 [[ True  True False ... False False False]
 [False False False ... False False  True]
 [False False False ... False False False]
 ...
 [False False False ... False False False]
 [False False False ... False False False]
 [False False False ... False False False]]
data_bar
 [[0 0 1 ... 1 1 1]
 [1 1 1 ... 1 1 0]
 [1 1 1 ... 1 1 1]
 ...
 [1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]]
cond prob
 [[0.351 0.014 0.007 ... 0.042 0.047 0.336]
 [0.002 0.099 0.638 ... 0.011 0.015 0.003]
 [0.002 0.002 0.012 ... 0.002 0.006 0.005]
 ...
 [0.002 0.003 0.002 ... 0.007 0.011 0.003]
 [0.006 0.003 0.019 ... 0.019 0.004 0.005]
 [0.002 0.002 0.002 ... 0.002 0.002 0.026]]
cond prob shape (5000, 20)
cond_prob_bar
 [[0.649 0.986 0.993 ... 0.958 0.953 0.664]
 [0.998 0.901 0.362 ... 0.989 0.985 0.997]
 [0.998 0.998 0.988 ... 0.998 0.994 0.995]
 ...
 [0.998 0.997 0.998 ... 0.993 0.989 0.997]
 [0.994 0.997 0.981 ... 0.981 0.996 0.995]
 [0.998 0.998 0.998 ... 0.998 0.998 0.974]]
cond_prob_bar shape

In [113]:
# Try decision tree with hard-coded maximum depth

dt_params = { 'max_depth': 16 }

dt_model = decision_tree_train(train_data, train_labels, dt_params)




{'left 0': {'left 22': {'left 1367': {'predicted': 0},
                        'right 1367': {'left 2135': {'left 5': {'left 3': {'predicted': 0},
                                                                'right 3': {'predicted': 0}},
                                                     'right 5': {'predicted': 0}},
                                       'right 2135': {'predicted': 15}}},
            'right 22': {'left 28': {'left 2': {'predicted': 8},
                                     'right 2': {'left 13': {'left 1203': {'left 108': {'left 20': {'predicted': 0},
                                                                                        'right 20': {'predicted': 0}},
                                                                           'right 108': {'predicted': 0}},
                                                             'right 1203': {'left 2423': {'left 75': {'predicted': 0},
                                                                           

                                                                                                                                                                                    'right 17': {'predicted': 11}},
                                                                                                                                                                        'right 86': {'left 165': {'left 24': {'predicted': 18},
                                                                                                                                                                                                  'right 24': {'predicted': 0}},
                                                                                                                                                                                     'right 165': {'left 344': {'predicted': 16},
                                                                                                                 

In [112]:
# Compute training accuracy

dt_train_predictions = decision_tree_predict(train_data, dt_model)
                                
dt_train_accuracy = np.mean(dt_train_predictions == train_labels)

print("Decision tree training accuracy: %f" % dt_train_accuracy)

NameError: name 'dt_model' is not defined

In [90]:
# Compute testing accuracy

dt_test_predictions = decision_tree_predict(test_data, dt_model)
                                
dt_test_accuracy = np.mean(dt_test_predictions == test_labels)

print("Decision tree testing accuracy: %f" % dt_test_accuracy)

NameError: name 'dt_model' is not defined

In [36]:
pwd

'/Users/Georgia 1/PycharmProjects/hw1'