In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
import numpy as np
from decision_tree import calculate_information_gain, decision_tree_train, decision_tree_predict
from naive_bayes import naive_bayes_train, naive_bayes_predict
from load_all_data import load_all_data


In [3]:
num_words, num_training, num_testing, train_data, test_data, train_labels, test_labels = load_all_data()

Found pickle file. Loading 20news data from file.
Doing so should be faster than loading from raw text, but if the file is corrupted, delete it and this script will automatically load from the raw text next time it is run.
Finished loading in 0.02 seconds.


In [4]:
d = 5000 # maximum number of features

In [5]:
# Filter features by information gain

gain = calculate_information_gain(train_data, train_labels)

print(gain)

# sort features by calculated information gain
ranks = gain.argsort()[::-1]

train_data = train_data[ranks[:d], :]
test_data = test_data[ranks[:d], :]

# convert training data to dense ndarray
train_data = train_data.toarray()
test_data = test_data.toarray()

[6.89207785e-03 5.72929455e-03 2.35420535e-02 ... 1.76640647e-12
 1.76640647e-12 1.76640647e-12]


In [70]:
# Try naive Bayes with hard-coded alpha value

nb_params = { 'alpha': 1.0 }

nb_model = naive_bayes_train(train_data, train_labels, nb_params)




11269 [480. 581. 572. 587. 575. 592. 582. 592. 596. 594. 598. 594. 591. 594.
 593. 599. 545. 564. 464. 376.]
11269.0
[0.04260785 0.05155461 0.05075737 0.0520861  0.05102312 0.05252901
 0.05164319 0.05252901 0.05288334 0.05270617 0.0530605  0.05270617
 0.05244043 0.05270617 0.05261759 0.05314908 0.04836567 0.05004872
 0.04119054 0.03339534] 1.0000000000000002
countxy
 [[168.]
 [  0.]
 [  0.]
 ...
 [  0.]
 [  2.]
 [  0.]]
20
reshape
 [[480. 581. 572. ... 564. 464. 376.]
 [480. 581. 572. ... 564. 464. 376.]
 [480. 581. 572. ... 564. 464. 376.]
 ...
 [480. 581. 572. ... 564. 464. 376.]
 [480. 581. 572. ... 564. 464. 376.]
 [480. 581. 572. ... 564. 464. 376.]] (5000, 20)
shape: (5000, 20) (5000, 20) (5000, 20)
prob xy smoothed
 [[0.35062241 0.01372213 0.00696864 ... 0.04240283 0.0472103  0.33597884]
 [0.00207469 0.09948542 0.63763066 ... 0.01060071 0.01502146 0.0026455 ]
 [0.00207469 0.00171527 0.01219512 ... 0.00176678 0.00643777 0.00529101]
 ...
 [0.00207469 0.00343053 0.00174216 ... 0.00

In [73]:
# Compute training accuracy

nb_train_predictions = naive_bayes_predict(train_data, nb_model)

nb_train_accuracy = np.mean(nb_train_predictions == train_labels)

print("Naive Bayes training accuracy: %f" % nb_train_accuracy)

print(train_labels[0:20])

data  [[ True False False ...  True False False]
 [False False False ... False False False]
 [False False False ... False False False]
 ...
 [False False False ... False False False]
 [False False False ... False False False]
 [False False False ... False False False]]
data_bar [[0 1 1 ... 0 1 1]
 [1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 ...
 [1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]]
(11269,)
cond prob [[0.35062241 0.01372213 0.00696864 ... 0.04240283 0.0472103  0.33597884]
 [0.00207469 0.09948542 0.63763066 ... 0.01060071 0.01502146 0.0026455 ]
 [0.00207469 0.00171527 0.01219512 ... 0.00176678 0.00643777 0.00529101]
 ...
 [0.00207469 0.00343053 0.00174216 ... 0.00706714 0.01072961 0.0026455 ]
 [0.00622407 0.00343053 0.01916376 ... 0.01943463 0.00429185 0.00529101]
 [0.00207469 0.00171527 0.00174216 ... 0.00176678 0.00214592 0.02645503]]
cond prob shape (5000, 20)
cond_prob_bar [[0.64937759 0.98627787 0.99303136 ... 0.95759717 0.9527897  0.66402116]
 [0.99792531 0.90051458 

In [72]:
# Compute testing accuracy

nb_test_predictions = naive_bayes_predict(test_data, nb_model)

nb_test_accuracy = np.mean(nb_test_predictions == test_labels)

print("Naive Bayes testing accuracy: %f" % nb_test_accuracy)

data  [[ True  True False ... False False False]
 [False False False ... False False  True]
 [False False False ... False False False]
 ...
 [False False False ... False False False]
 [False False False ... False False False]
 [False False False ... False False False]]
data_bar [[0 0 1 ... 1 1 1]
 [1 1 1 ... 1 1 0]
 [1 1 1 ... 1 1 1]
 ...
 [1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]]
(7505,)
cond prob [[0.35062241 0.01372213 0.00696864 ... 0.04240283 0.0472103  0.33597884]
 [0.00207469 0.09948542 0.63763066 ... 0.01060071 0.01502146 0.0026455 ]
 [0.00207469 0.00171527 0.01219512 ... 0.00176678 0.00643777 0.00529101]
 ...
 [0.00207469 0.00343053 0.00174216 ... 0.00706714 0.01072961 0.0026455 ]
 [0.00622407 0.00343053 0.01916376 ... 0.01943463 0.00429185 0.00529101]
 [0.00207469 0.00171527 0.00174216 ... 0.00176678 0.00214592 0.02645503]]
cond prob shape (5000, 20)
cond_prob_bar [[0.64937759 0.98627787 0.99303136 ... 0.95759717 0.9527897  0.66402116]
 [0.99792531 0.90051458 0

In [26]:
# Try decision tree with hard-coded maximum depth

dt_params = { 'max_depth': 16 }

dt_model = decision_tree_train(train_data, train_labels, dt_params)




/Users/Georgia 1/PycharmProjects/hw1/decision_tree.py:45: RuntimeWarning: invalid value encountered in true_divide
  prob_x = num_x / n


KeyboardInterrupt: 

In [ ]:
# Compute training accuracy_testing

dt_train_predictions = predict_points(train_data, dt_model)
                                
dt_train_accuracy = np.mean(dt_train_predictions == train_labels)
#print(dt_train_predictions[:20])
#print('len_train_pred',len(dt_train_predictions))
#print('train_lb',train_labels)

                           
#print('len_train_lb',len(train_labels))
print("Decision tree training accuracy: %f" % dt_train_accuracy)

In [ ]:
# Compute training accuracy

dt_train_predictions = decision_tree_predict(train_data, dt_model)
                                
dt_train_accuracy = np.mean(dt_train_predictions == train_labels)

print("Decision tree training accuracy: %f" % dt_train_accuracy)

In [ ]:
# Compute testing accuracy

dt_test_predictions = decision_tree_predict(test_data, dt_model)
                                
dt_test_accuracy = np.mean(dt_test_predictions == test_labels)

print("Decision tree testing accuracy: %f" % dt_test_accuracy)

In [36]:
pwd

'/Users/Georgia 1/PycharmProjects/hw1'